import { type Recipe } from "@/components/nutrition/RecipeCard"

export const RECIPES = {
  cottageCheesEggs: {
    name: "Cottage Cheese Scrambled Eggs",
    sourceLabel: "Oh Snap Macros",
    sourceUrl: "https://ohsnapmacros.com/cottage-cheese-and-scrambled-eggs/",
    mealType: "Breakfast",
    prepMins: 5,
    storesDays: "same day",
    calories: 240,
    proteinG: 30,
    carbsG: 3,
    fatG: 10,
    description: "2 whole eggs + 3 egg whites scrambled with ¼ cup low-fat cottage cheese, salt, pepper, and optional hot sauce. The cottage cheese melts in and adds creaminess along with a protein boost.",
    servingNote: "Makes 1 serving. Eat immediately — scrambled eggs don't store well.",
    ingredients: [
      { qty: 2, unit: "", item: "large eggs", isWhole: true },
      { qty: 3, unit: "", item: "egg whites", isWhole: true },
      { qty: 0.25, unit: "cup", item: "low-fat cottage cheese" },
      { qty: 0, unit: "to taste", item: "salt, pepper, hot sauce" },
    ],
  } satisfies Recipe,

  overnightOats: {
    name: "Greek Yogurt Overnight Oats",
    sourceLabel: "The Plant Based School",
    sourceUrl: "https://theplantbasedschool.com/greek-yogurt-overnight-oats/",
    mealType: "Breakfast",
    prepMins: 10,
    storesDays: "up to 5 days (refrigerated)",
    calories: 395,
    proteinG: 33,
    carbsG: 47,
    fatG: 9,
    description: "⅓ cup rolled oats + 1 cup plain Greek yogurt + ½ cup milk + 1 tbsp chia seeds + ½ cup berries + 1 tsp honey. Mix the night before, refrigerate, and eat cold in the morning. Batch-prep 4–5 jars at once.",
    servingNote: "Makes 1 serving. Scale up easily for the week.",
    ingredients: [
      { qty: 0.33, unit: "cup", item: "rolled oats" },
      { qty: 1, unit: "cup", item: "plain Greek yogurt" },
      { qty: 0.5, unit: "cup", item: "milk" },
      { qty: 1, unit: "tbsp", item: "chia seeds" },
      { qty: 0.5, unit: "cup", item: "mixed berries" },
      { qty: 1, unit: "tsp", item: "honey" },
    ],
  } satisfies Recipe,

  chickenSalad: {
    name: "High-Protein Chicken Salad",
    sourceLabel: "Coconuts & Kettlebells",
    sourceUrl: "https://coconutsandkettlebells.com/high-protein-chicken-salad/",
    mealType: "Lunch",
    prepMins: 10,
    storesDays: "4 days (refrigerated)",
    calories: 225,
    proteinG: 30,
    carbsG: 7,
    fatG: 8,
    description: "6oz shredded cooked chicken + 6 tbsp plain Greek yogurt (instead of mayo) + 2 tsp olive oil + diced celery, red onion, and bell pepper + Dijon mustard + herbs. Serve over greens, in a wrap, or with whole grain crackers.",
    servingNote: "Makes 2 servings. Ingredients shown per 1 serving.",
    batchServings: 2,
    ingredients: [
      { qty: 6, unit: "oz", item: "cooked chicken breast, shredded" },
      { qty: 6, unit: "tbsp", item: "plain Greek yogurt" },
      { qty: 2, unit: "tsp", item: "olive oil" },
      { qty: 0.5, unit: "cup", item: "celery, finely diced" },
      { qty: 0.25, unit: "cup", item: "red onion, diced" },
      { qty: 0.25, unit: "cup", item: "bell pepper, diced" },
      { qty: 1, unit: "tbsp", item: "Dijon mustard" },
      { qty: 0, unit: "to taste", item: "salt, pepper, dill, parsley" },
    ],
  } satisfies Recipe,

  mediterraneanBowl: {
    name: "Mediterranean Chicken Quinoa Bowl",
    sourceLabel: "Nourish Move Love",
    sourceUrl: "https://www.nourishmovelove.com/high-protein-lunch/",
    mealType: "Lunch",
    prepMins: 20,
    storesDays: "4 days (refrigerated)",
    calories: 390,
    proteinG: 38,
    carbsG: 36,
    fatG: 12,
    description: "4oz chicken breast marinated in lemon juice, olive oil, and oregano, grilled or baked. Served over ¾ cup cooked quinoa with cucumber, cherry tomatoes, red onion, and a tablespoon of tzatziki.",
    servingNote: "One of the most nutritionally complete single-bowl meals. Prep the chicken and quinoa in bulk on Sunday.",
    ingredients: [
      { qty: 4, unit: "oz", item: "chicken breast, grilled" },
      { qty: 0.75, unit: "cup", item: "cooked quinoa" },
      { qty: 0.5, unit: "cup", item: "cucumber, diced" },
      { qty: 0.5, unit: "cup", item: "cherry tomatoes, halved" },
      { qty: 2, unit: "tbsp", item: "red onion, diced" },
      { qty: 1, unit: "tbsp", item: "tzatziki" },
      { qty: 1, unit: "tsp", item: "olive oil" },
      { qty: 1, unit: "tsp", item: "lemon juice" },
      { qty: 0, unit: "to taste", item: "oregano, salt, pepper" },
    ],
  } satisfies Recipe,

  tunaSalad: {
    name: "No-Mayo Tuna Salad",
    sourceLabel: "Fit Healthy Macros",
    sourceUrl: "https://fithealthymacros.com/recipes/classic-tuna-salad/",
    mealType: "Lunch",
    prepMins: 7,
    storesDays: "3 days (refrigerated)",
    calories: 200,
    proteinG: 32,
    carbsG: 5,
    fatG: 6,
    description: "One 5oz can tuna in water (drained) + 3 tbsp plain Greek yogurt + 1 tsp olive oil + diced celery + red onion + dill + squeeze of lemon. Serve over greens or with whole grain crackers.",
    servingNote: "Sub Greek yogurt for mayo — same creaminess, significantly more protein and less fat. Shelf-stable ingredients make this a reliable fallback meal.",
    ingredients: [
      { qty: 5, unit: "oz", item: "canned tuna in water, drained" },
      { qty: 3, unit: "tbsp", item: "plain Greek yogurt" },
      { qty: 1, unit: "tsp", item: "olive oil" },
      { qty: 2, unit: "stalks", item: "celery, diced", isWhole: true },
      { qty: 2, unit: "tbsp", item: "red onion, diced" },
      { qty: 1, unit: "tbsp", item: "lemon juice" },
      { qty: 0, unit: "to taste", item: "dill, salt, pepper" },
    ],
  } satisfies Recipe,

  beefBroccoli: {
    name: "Ground Beef & Broccoli Stir-Fry",
    sourceLabel: "Oh Snap Macros",
    sourceUrl: "https://ohsnapmacros.com/ground-beef-and-broccoli/",
    mealType: "Dinner",
    prepMins: 15,
    storesDays: "5 days (refrigerated)",
    calories: 402,
    proteinG: 43,
    carbsG: 14,
    fatG: 20,
    description: "8oz 93% lean ground beef + 3 cups broccoli in a light sauce of coconut aminos and hoisin, with fresh ginger, garlic, and a touch of sesame oil. Serve over cauliflower rice or white rice.",
    servingNote: "One of the highest-protein dinners in this plan. Add rice if you need more carbs — the stir-fry itself is low-carb.",
    ingredients: [
      { qty: 8, unit: "oz", item: "93% lean ground beef" },
      { qty: 3, unit: "cups", item: "broccoli florets" },
      { qty: 2, unit: "tbsp", item: "coconut aminos" },
      { qty: 1, unit: "tsp", item: "hoisin sauce" },
      { qty: 1, unit: "tsp", item: "sesame oil" },
      { qty: 1, unit: "tsp", item: "fresh ginger, grated" },
      { qty: 2, unit: "", item: "garlic cloves, minced", isWhole: true },
    ],
  } satisfies Recipe,

  salmon: {
    name: "Honey-Glazed Salmon with Asparagus",
    sourceLabel: "Real Food Dietitians",
    sourceUrl: "https://therealfooddietitians.com/salmon-recipes/",
    mealType: "Dinner",
    prepMins: 25,
    storesDays: "3 days (refrigerated)",
    calories: 355,
    proteinG: 38,
    carbsG: 12,
    fatG: 16,
    description: "6oz salmon fillet glazed with 1 tsp honey + 1 tsp Dijon mustard + 1 tsp low-sodium soy sauce. Sheet pan at 400°F/200°C for 18–20 min alongside asparagus drizzled with olive oil.",
    servingNote: "Omega-3 fatty acids from salmon support muscle protein synthesis and recovery. One of the easiest high-protein meals to prepare.",
    ingredients: [
      { qty: 6, unit: "oz", item: "salmon fillet" },
      { qty: 1, unit: "tsp", item: "honey" },
      { qty: 1, unit: "tsp", item: "Dijon mustard" },
      { qty: 1, unit: "tsp", item: "low-sodium soy sauce" },
      { qty: 8, unit: "spears", item: "asparagus", isWhole: true },
      { qty: 1, unit: "tsp", item: "olive oil" },
      { qty: 0, unit: "to taste", item: "salt and pepper" },
    ],
  } satisfies Recipe,

  turkeyMeatballs: {
    name: "Baked Turkey Meatballs",
    sourceLabel: "Taste and See",
    sourceUrl: "https://tasteandsee.com/healthy-meal-prep-baked-turkey-meatballs/",
    mealType: "Dinner",
    prepMins: 30,
    storesDays: "4 days fresh · 6 months frozen",
    calories: 275,
    proteinG: 32,
    carbsG: 8,
    fatG: 11,
    description: "1 lb 93% lean ground turkey + ¼ cup Parmesan + ¼ cup breadcrumbs + egg + fresh parsley + garlic + Italian seasoning. Roll into balls, bake at 400°F/200°C for 18–20 min. Serve with marinara sauce.",
    servingNote: "Macros for 6 meatballs (1 of 3 servings). Excellent batch-cook option — freeze in portions of 6.",
    batchServings: 3,
    ingredients: [
      { qty: 1, unit: "lb", item: "93% lean ground turkey" },
      { qty: 0.25, unit: "cup", item: "Parmesan, finely grated" },
      { qty: 0.25, unit: "cup", item: "breadcrumbs" },
      { qty: 1, unit: "", item: "large egg", isWhole: true },
      { qty: 2, unit: "tbsp", item: "fresh parsley, chopped" },
      { qty: 2, unit: "", item: "garlic cloves, minced", isWhole: true },
      { qty: 1, unit: "tsp", item: "Italian seasoning" },
      { qty: 0.5, unit: "tsp", item: "salt" },
    ],
  } satisfies Recipe,

  cottageCheeseBowl: {
    name: "Whipped Cottage Cheese Bowl",
    sourceLabel: "Oh Snap Macros",
    sourceUrl: "https://ohsnapmacros.com/cottage-cheese/",
    mealType: "Snack",
    prepMins: 5,
    storesDays: "2 days (refrigerated)",
    calories: 220,
    proteinG: 26,
    carbsG: 22,
    fatG: 5,
    description: "1 cup low-fat cottage cheese blended smooth (optional) + topped with mixed berries, a drizzle of honey, and optional granola or sliced almonds. Can also add a spoonful of nut butter for extra fat.",
    servingNote: "One of the highest protein-per-calorie snacks available. Blending creates a creamy texture that tastes indulgent.",
    ingredients: [
      { qty: 1, unit: "cup", item: "low-fat cottage cheese" },
      { qty: 0.5, unit: "cup", item: "mixed berries" },
      { qty: 1, unit: "tsp", item: "honey" },
      { qty: 2, unit: "tbsp", item: "granola or sliced almonds" },
    ],
  } satisfies Recipe,
}

export type RecipeKey = keyof typeof RECIPES
