import { type Recipe } from "@/components/nutrition/RecipeCard"

export const RECIPES = {
  cottageCheesEggs: {
    name: "Cottage Cheese Scrambled Eggs",
    sourceLabel: "Oh Snap Macros",
    sourceUrl: "https://ohsnapmacros.com/cottage-cheese-and-scrambled-eggs/",
    mealType: "Breakfast",
    prepMins: 5,
    storesDays: "same day",
    calories: 233,
    proteinG: 29,
    carbsG: 3,
    fatG: 11,
    description: "3 whole eggs scrambled with ¼ cup low-fat cottage cheese, salt, pepper, and optional hot sauce. The cottage cheese melts in and adds creaminess along with a protein boost.",
    servingNote: "Makes 1 serving. Eat immediately — scrambled eggs don't store well.",
  } satisfies Recipe,

  overnightOats: {
    name: "Greek Yogurt Overnight Oats",
    sourceLabel: "The Plant Based School",
    sourceUrl: "https://theplantbasedschool.com/greek-yogurt-overnight-oats/",
    mealType: "Breakfast",
    prepMins: 10,
    storesDays: "up to 5 days (refrigerated)",
    calories: 400,
    proteinG: 32,
    carbsG: 45,
    fatG: 8,
    description: "½ cup rolled oats + ¾ cup plain Greek yogurt + ½ cup milk + 1 tbsp chia seeds + berries. Mix the night before, refrigerate, and eat cold in the morning. Batch-prep 4–5 jars at once.",
    servingNote: "Makes 1 serving. Scale up easily for the week.",
  } satisfies Recipe,

  chickenSalad: {
    name: "High-Protein Chicken Salad",
    sourceLabel: "Coconuts & Kettlebells",
    sourceUrl: "https://coconutsandkettlebells.com/high-protein-chicken-salad/",
    mealType: "Lunch",
    prepMins: 10,
    storesDays: "4 days (refrigerated)",
    calories: 250,
    proteinG: 30,
    carbsG: 8,
    fatG: 8,
    description: "6oz shredded cooked chicken + ¼ cup Greek yogurt (instead of mayo) + diced celery, red onion, and bell pepper + Dijon mustard + herbs. Serve over greens, in a wrap, or with whole grain crackers.",
    servingNote: "Makes 2 servings. Protein per serving from Greek yogurt is significantly higher than traditional mayo-based versions.",
  } satisfies Recipe,

  mediterraneanBowl: {
    name: "Mediterranean Chicken Quinoa Bowl",
    sourceLabel: "Nourish Move Love",
    sourceUrl: "https://www.nourishmovelove.com/high-protein-lunch/",
    mealType: "Lunch",
    prepMins: 20,
    storesDays: "4 days (refrigerated)",
    calories: 400,
    proteinG: 35,
    carbsG: 40,
    fatG: 10,
    description: "5oz chicken breast marinated in lemon juice, olive oil, and oregano, grilled or baked. Served over 1 cup cooked quinoa with cucumber, cherry tomatoes, red onion, and a tablespoon of tzatziki.",
    servingNote: "One of the most nutritionally complete single-bowl meals. Prep the chicken and quinoa in bulk on Sunday.",
  } satisfies Recipe,

  tunaSalad: {
    name: "No-Mayo Tuna Salad",
    sourceLabel: "Fit Healthy Macros",
    sourceUrl: "https://fithealthymacros.com/recipes/classic-tuna-salad/",
    mealType: "Lunch",
    prepMins: 7,
    storesDays: "3 days (refrigerated)",
    calories: 195,
    proteinG: 28,
    carbsG: 5,
    fatG: 7,
    description: "One 5oz can tuna in water (drained) + 3 tbsp plain Greek yogurt + diced celery + red onion + dill + squeeze of lemon. Serve over greens or with whole grain crackers.",
    servingNote: "Sub Greek yogurt for mayo — same creaminess, significantly more protein and less fat. Shelf-stable ingredients make this a reliable fallback meal.",
  } satisfies Recipe,

  beefBroccoli: {
    name: "Ground Beef & Broccoli Stir-Fry",
    sourceLabel: "Oh Snap Macros",
    sourceUrl: "https://ohsnapmacros.com/ground-beef-and-broccoli/",
    mealType: "Dinner",
    prepMins: 15,
    storesDays: "5 days (refrigerated)",
    calories: 402,
    proteinG: 43,
    carbsG: 14,
    fatG: 20,
    description: "8oz 93/7 lean ground beef + 3 cups broccoli in a sauce of coconut aminos, hoisin, oyster sauce, rice vinegar, fresh ginger, and garlic. Serve over cauliflower rice or white rice.",
    servingNote: "One of the highest-protein dinners in this plan. Add rice if you need more carbs — the stir-fry itself is low-carb.",
  } satisfies Recipe,

  salmon: {
    name: "Honey-Glazed Salmon with Asparagus",
    sourceLabel: "Real Food Dietitians",
    sourceUrl: "https://therealfooddietitians.com/salmon-recipes/",
    mealType: "Dinner",
    prepMins: 25,
    storesDays: "3 days (refrigerated)",
    calories: 380,
    proteinG: 38,
    carbsG: 18,
    fatG: 16,
    description: "6oz salmon fillet glazed with 1 tsp honey + 1 tsp Dijon mustard + 1 tsp low-sodium soy sauce. Sheet pan at 400°F/200°C for 18–20 min alongside asparagus drizzled with olive oil.",
    servingNote: "Omega-3 fatty acids from salmon support muscle protein synthesis and recovery. One of the easiest high-protein meals to prepare.",
  } satisfies Recipe,

  turkeyMeatballs: {
    name: "Baked Turkey Meatballs",
    sourceLabel: "Taste and See",
    sourceUrl: "https://tasteandsee.com/healthy-meal-prep-baked-turkey-meatballs/",
    mealType: "Dinner",
    prepMins: 30,
    storesDays: "4 days fresh · 6 months frozen",
    calories: 260,
    proteinG: 32,
    carbsG: 12,
    fatG: 9,
    description: "1 lb 93% lean ground turkey + ¼ cup Parmesan + ¼ cup almond flour + egg + fresh parsley + garlic + Italian seasoning. Roll into balls, bake at 400°F/200°C for 18–20 min. Serve with marinara sauce.",
    servingNote: "Macros for 6 meatballs. Excellent batch-cook option — freeze in portions of 6. Serve with pasta, rice, or zucchini noodles.",
  } satisfies Recipe,

  cottageCheeseBowl: {
    name: "Whipped Cottage Cheese Bowl",
    sourceLabel: "Oh Snap Macros",
    sourceUrl: "https://ohsnapmacros.com/cottage-cheese/",
    mealType: "Snack",
    prepMins: 5,
    storesDays: "2 days (refrigerated)",
    calories: 220,
    proteinG: 26,
    carbsG: 22,
    fatG: 5,
    description: "1 cup low-fat cottage cheese blended smooth (optional) + topped with mixed berries, a drizzle of honey, and optional almonds or granola. Can also add a spoonful of nut butter for extra fat.",
    servingNote: "One of the highest protein-per-calorie snacks available. Blending creates a creamy texture that tastes indulgent.",
  } satisfies Recipe,
}

export type RecipeKey = keyof typeof RECIPES
