export const COURSE_PRICE_CENTS = 4700
export const COURSE_WITH_TRACKER_PRICE_CENTS = 6400
export const COURSE_PRICE_DISPLAY = "$47"
export const COURSE_WITH_TRACKER_PRICE_DISPLAY = "$64"
export const COURSE_REGULAR_PRICE_DISPLAY = "$97"

export const NUTRITION_COURSE_PRICE_CENTS = 6700
export const NUTRITION_COURSE_PRICE_DISPLAY = "$67"
export const NUTRITION_COURSE_REGULAR_PRICE_DISPLAY = "$127"
