
export const COURSE_PRICE_CENTS = 9700
export const COURSE_WITH_TRACKER_PRICE_CENTS = 11400 // 9700 + 1700
export const COURSE_PRICE_DISPLAY = "$97"
export const COURSE_WITH_TRACKER_PRICE_DISPLAY = "$114"
export const COURSE_REGULAR_PRICE_DISPLAY = "$147"

export const NUTRITION_COURSE_PRICE_CENTS = 7700
export const NUTRITION_COURSE_PRICE_DISPLAY = "$77"
export const NUTRITION_COURSE_REGULAR_PRICE_DISPLAY = "$127"

export const BUNDLE_PRICE_CENTS = 13700
export const BUNDLE_PRICE_DISPLAY = "$137"
export const BUNDLE_INDIVIDUAL_TOTAL_DISPLAY = "$174"
export const BUNDLE_SAVINGS_DISPLAY = "$37"

// Masterclass — monthly subscription
export const MASTERCLASS_MONTHLY_CENTS = 2700
export const MASTERCLASS_6MONTH_CENTS = 13700
export const MASTERCLASS_ANNUAL_CENTS = 19700
export const MASTERCLASS_MONTHLY_DISPLAY = "$27"
export const MASTERCLASS_6MONTH_DISPLAY = "$137"
export const MASTERCLASS_ANNUAL_DISPLAY = "$197"
export const MASTERCLASS_6MONTH_PER_MONTH_DISPLAY = "$22.83"
export const MASTERCLASS_ANNUAL_PER_MONTH_DISPLAY = "$16.42"
